---
# tasks file for nginx

-name: updating the yum repository
 yum: name='*' state=latest

-name: installing nginx
 yum: name=nginx state=latest

-name: checking the nginx version
 shell: nginx -v
 register: nginx_version

-name: showing the nginx version
 debug: msg={{ nginx_version }}
